spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %X{requestId} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:hsqldb:mem:testdb;sql.syntax_pgs=true
    username: sa
    password: ''
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  error:
    include-stacktrace: always

logging:
  level:
    ru:
      sadv1r:
        cloud: trace
ru:
  sadv1r:
    cloud:
      link-shortener:
        base-url: http://localhost:8080
