version: "3"
services:
  link-shortener:
    image: sadv1r/link-shortener
#    restart: always
    environment:
      POSTGRES_URL: jdbc:postgresql://localhost:5432/cloud
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  cloud_postgres:
    image: postgres
    container_name: cloud_postgres
#    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
