---
- name: Set a hostname
  hostname:
    name: "{{ ansible_host }}"

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: "permissive"

- name: Update system packages
  package:
    name: "*"
    state: latest

#- name: Install some packages needed to configure the nodes
#  package:
#    name: "{{ item }}"
#  loop:
#    - "{{ basic_packages }}"

- name: Disable firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no